### GET api/user
GET http://localhost:8080/api/user

### POST api/user
POST http://localhost:8080/api/user

{
	"name": "haquocdat",
	"password": "12345678",
	"email": "wwwdatha543@gmail.com",
	"age": 20
}

### DELETE api/user
DELETE http://localhost:8080/api/user

{
	"name": "haquocdat",
	"password": "12345678"
}

### POST api/user/login
POST http://localhost:8080/api/user/login

{
	"name": "haquocdat",
	"password": "12345678"
}

### POST api/user/password
PATCH http://localhost:8080/api/user/password

{
	"name": "haquocdat",
	"password": "12345678",
	"new_password": "12345679"
}

