@SCHEME = http
@HOST = localhost
@PORT = 8080

### GET api/user/all
GET {{SCHEME}}://{{HOST}}:{{PORT}}/api/user/all

### POST api/user
POST {{SCHEME}}://{{HOST}}:{{PORT}}/api/user

{
	"name": "haquocdat",
	"password": "12345678",
	"email": "wwwdatha543@gmail.com"
}

### GET api/user
GET {{SCHEME}}://{{HOST}}:{{PORT}}/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTE4MDYzNTAsImlhdCI6MTc1MTcxOTk1MCwiaXAiOiI6OjEiLCJ1c2VybmFtZSI6ImhhcXVvY2RhdCJ9.NyPXsJajJuG9_2KORadJRb_oJNI8OLjI1nQXxTXOWnU

### DELETE api/user
DELETE {{SCHEME}}://{{HOST}}:{{PORT}}/api/user

{
	"name": "haquocdat",
	"password": "12345678"
}

### POST api/user/login
POST {{SCHEME}}://{{HOST}}:{{PORT}}/api/user/login

{
	"name": "haquocdat",
	"password": "12345678"
}

### POST api/user/password
PATCH {{SCHEME}}://{{HOST}}:{{PORT}}/api/user/password

{
	"name": "haquocdat",
	"password": "12345679",
	"new_password": "12345678"
}

### POST api/user
PATCH {{SCHEME}}://{{HOST}}:{{PORT}}/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTE4MDYzNTAsImlhdCI6MTc1MTcxOTk1MCwiaXAiOiI6OjEiLCJ1c2VybmFtZSI6ImhhcXVvY2RhdCJ9.NyPXsJajJuG9_2KORadJRb_oJNI8OLjI1nQXxTXOWnU

{
	"dob": "2004-10-26",
	"role": "Director"
}

### POST api/user
PUT {{SCHEME}}://{{HOST}}:{{PORT}}/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTE4MDYzNTAsImlhdCI6MTc1MTcxOTk1MCwiaXAiOiI6OjEiLCJ1c2VybmFtZSI6ImhhcXVvY2RhdCJ9.NyPXsJajJuG9_2KORadJRb_oJNI8OLjI1nQXxTXOWnU

{
	"dob": "2004-11-26",
	"role": "Manager",
	"address": "South Vietnam"
}
