### GET api/user/all
GET http://localhost:8080/api/user/all

### POST api/user
POST http://localhost:8080/api/user

{
	"name": "haquocdat",
	"password": "12345678",
	"email": "wwwdatha543@gmail.com"
}

### GET api/user
GET http://localhost:8080/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTE4MDYzNTAsImlhdCI6MTc1MTcxOTk1MCwiaXAiOiI6OjEiLCJ1c2VybmFtZSI6ImhhcXVvY2RhdCJ9.NyPXsJajJuG9_2KORadJRb_oJNI8OLjI1nQXxTXOWnU

### DELETE api/user
DELETE http://localhost:8080/api/user

{
	"name": "haquocdat",
	"password": "12345678"
}

### POST api/user/login
POST http://localhost:8080/api/user/login

{
	"name": "haquocdat",
	"password": "12345678"
}

### POST api/user/password
PATCH http://localhost:8080/api/user/password

{
	"name": "haquocdat",
	"password": "12345679",
	"new_password": "12345678"
}

### POST api/user
PATCH http://localhost:8080/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTE4MDYzNTAsImlhdCI6MTc1MTcxOTk1MCwiaXAiOiI6OjEiLCJ1c2VybmFtZSI6ImhhcXVvY2RhdCJ9.NyPXsJajJuG9_2KORadJRb_oJNI8OLjI1nQXxTXOWnU

{
	"dob": "2004-10-26",
	"role": "Director"
}

### POST api/user
PUT http://localhost:8080/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTE4MDYzNTAsImlhdCI6MTc1MTcxOTk1MCwiaXAiOiI6OjEiLCJ1c2VybmFtZSI6ImhhcXVvY2RhdCJ9.NyPXsJajJuG9_2KORadJRb_oJNI8OLjI1nQXxTXOWnU

{
	"dob": "2004-11-26",
	"role": "Manager",
	"address": "South Vietnam"
}
